server.port=8083
spring.datasource.name=books
spring.datasource.url=jdbc:mysql://localhost:3306/books?ServerTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.web=DEBUG
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect